### ISSUE TITLE
Bug: Share icons not showing up

### ISSUE THREAD

**Issue by fabioelia** [f1v/f1v-blog#13]
![image](https://user-images.githubusercontent.com/633247/98285212-39b69f80-1f70-11eb-8c29-1bc0df79c5da.png)

**Comment by trybick** [comment]
Can no longer replicate 

<img width="483" alt="Screen Shot 2021-08-29 at 12 55 14 PM" src="https://user-images.githubusercontent.com/39889198/131258651-41b01ecd-2220-4634-8a80-c2e9ca2eae3e.png">
