### ISSUE TITLE
Optimize images

### ISSUE THREAD

**Issue by trybick** [f1v/f1v-blog#7]
I noticed one of the images in a post is 1.74 MB (oops). We could manually optimize them then re-save them in the project or maybe gatsby has a plugin to re-size.

**Comment by fabioelia** [comment]
Please invite me + veiko as admins to the netlifly setup.

In Netlifly they have a setting to auto-optimize assets

**Comment by trybick** [comment]
@fabioelia I tried adding you but it said it cost $15 a month to add more people :( 

However I found the setting and enabled the compress image setting.

I also found a guide that might work to transfer the netlify account to your account. Should I work on that today?
<img width="1265" alt="Screen Shot 2020-10-02 at 7 49 46 AM" src="https://user-images.githubusercontent.com/39889198/94920205-da9ed000-0483-11eb-85b3-7f053068eae0.png">

**Comment by trybick** [comment]
I think the netlify optimization is working - see screenshot of image size. Closing but feel free to re-open if any concerns @fabioelia 

![Screen Shot 2020-10-09 at 9 08 23 AM](https://user-images.githubusercontent.com/39889198/95586697-07685f80-0a0f-11eb-9b7d-b851664db12c.png)
